blank_issues_enabled: true
contact_links:
  - name: 📚 Documentation
    url: https://github.com/skarllot/azure-keyvault-reference#guide
    about: Read our documentation.
  - name: ⭐ Sponsor Raiqub Expressions
    url: https://www.buymeacoffee.com/skarllot
    about: Help the continued development.
  - name: 💬 Ask on Github Discussions
    url: https://github.com/skarllot/azure-keyvault-reference/discussions
    about: The best place for asking general purpose questions.
